# -*- coding: utf-8 -*-
"""Aula1_Optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kchgzwCiIwKdjkMMuMw_C1vPFy8_QOOu

### **The purpose of the code is to mathematically model the business's finances (by defining costs, revenue, and profit) and generate a graph that illustrates how production costs vary with the number of magazines printed.**
"""

import numpy as np
import matplotlib.pyplot as plt

# Create an array of integers from 0 to 9
quantity = np.arange(10)

# 1. The Cost Function
def cost(q):
    # Base cost of 50, with a quadratic increase as production deviates from 2
    return 50 + 5 * (q - 2)**2

# 2. Defining Revenue
def revenue(q):
    # Let's assume that each batch of magazines is sold at a fixed price
    # Example: The selling price is 40 (which, on the code scale, would be $40,000)
    preco_venda = 40
    return preco_venda * q

# 3. The Profit Function
def profit(q):
    """
    O lucro é simplesmente a Receita (dinheiro que entra)
    menos o Custo (dinheiro que sai).
    """
    return revenue(q) - cost(q)


# Plot cost versus quantity
plt.plot(quantity, cost(quantity))
plt.xlabel('Quantity (thousands)')
plt.ylabel('Cost ($ K)')
plt.show()

"""### The purpose of the code is to identify and display the optimal production quantity required to maximize profit."""

# Calculate the profit for every quantity
profits = profit(quantity)

# Find the maximum profit
max_profit = profits.max()

# Find the optimal quantity
max_profit_ind = np.argmax(profits)
optimal_quantity = quantity[max_profit_ind]

# Print the results
print(f"You need to print {optimal_quantity * 1000} magazines to make the maximum profit of ${max_profit * 1000}.")
